version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starter-template
    networks:
      - message_broker_network
    env_file:
      - ./envs/.env.development
    environment:
      - NODE_ENV=production
      - TZ=Europe/Moscow
    ports:
      - "5690:5690"
    volumes:
      - ./envs:/app/envs
    restart: unless-stopped

networks:
  message_broker_network:
    driver: bridge